version: '3.8'
services:
  nest:
    build:
      args:
        - NODE_VER=22
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
      - '9229:9229'

volumes:
  node_modules:
