export const AT_STRATEGIEST = 'AtStrategiest';
export const RT_STRATEGIEST = 'RtStrategiest';

export const LOGIN_USER_REPOSITORY = 'LOGIN_USER_REPOSITORY';
export const REGISTER_USER_REPOSITORY = 'REGISTER_USER_REPOSITORY';
export const LOG_OUT_USER_REPOSITORY = 'LOG_OUT_USER_REPOSITORY';
export const TOKEN_GENERATE_REPOSITORY = 'TOKEN_GENERATE_REPOSITORY';
