export const USER_REPOSITORY_PORT = 'USER_REPOSITORY_PORT';
export const CREATE_REPOSITORY_PORT = 'CREATE_REPOSITORY_PORT';
export const FIND_REPOSITORY_PORT = 'FIND_REPOSITORY_PORT';
export const UPDATE_USER_REPOSITORY_PORT = 'UPDATE_USER_REPOSITORY_PORT';
export const DELETE_USER_REPOSITORY_PORT = 'DELETE_USER_REPOSITORY_PORT';
