import {
  ASSIGN_ROLE_PERMISSION_REPOSITORY,
  CREATE_ROLE_REPOSITORY,
  FIND_ROLE_REPOSITORY,
} from './token-injection';

export {
  CREATE_ROLE_REPOSITORY,
  FIND_ROLE_REPOSITORY,
  ASSIGN_ROLE_PERMISSION_REPOSITORY,
};
