export const CREATE_ROLE_REPOSITORY = 'CREATE_ROLE_REPOSITORY';
export const FIND_ROLE_REPOSITORY = 'FIND_ROLE_REPOSITORY';
export const ASSIGN_ROLE_PERMISSION_REPOSITORY =
  'ASSIGN_ROLE_PERMISSION_REPOSITORY';
export const ROLES_PERMISSIONS = 'ROLES_PERMISSIONS';
