import {
  CREATE_PERMISSION_REPOSITORY,
  DELETE_PERMISSION_REPOSITORY,
  FIND_PERMISSION_REPOSITORY,
  UPDATE_PERMISSION_REPOSITORY,
} from './permissions.token';

export {
  CREATE_PERMISSION_REPOSITORY,
  FIND_PERMISSION_REPOSITORY,
  UPDATE_PERMISSION_REPOSITORY,
  DELETE_PERMISSION_REPOSITORY,
};
