CREATE TABLE todo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content VARCHAR(255),
    is_done BOOLEAN NOT NULL DEFAULT false,
    createdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateddate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `user` (
    `id` INT AUTO_INCREMENT NOT NULL,
    `username` VARCHAR(255) NOT NULL,
    `password` TEXT NOT NULL,
    `createdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updateddate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `last_login` TIMESTAMP,
    `hach_refresh_token` VARCHAR(255),

    PRIMARY KEY (`id`),
    UNIQUE KEY `UINQUE_KEY_user_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;