export const CREATE_PERMISSION_REPOSITORY = 'CREATE_PERMISSION_REPOSITORY';
export const FIND_PERMISSION_REPOSITORY = 'FIND_PERMISSION_REPOSITORY';
export const UPDATE_PERMISSION_REPOSITORY = 'UPDATE_PERMISSION_REPOSITORY';
export const DELETE_PERMISSION_REPOSITORY = 'DELETE_PERMISSION_REPOSITORY';
